[package]
name = "zed_serena_context_server"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
schemars = "1.0"
zed_extension_api = "0.6.0"
